version: '3'
services:
    tags_service:
        build: ./core
        ports:
            - "5000:8000"
        volumes:
            - .:/go/src/github.com/ignoshi/core
    snippets_service:
        build: ./snippets
        ports:
            - "5001:8000"
        volumes:
            - .:/go/src/github.com/ignoshi/snippets
    ui_service:
        build: 
            context: ./ignoshi
            dockerfile: Dockerfile.dev
        ports:
            - "8000:8080"
        volumes:
            - .:/app
    api_gateway:
        build: ./api_gateway
        ports:
            - "8080:8080"
            - "8443:8443"
            - "8081:8081"
            - "8444:8444"
    mongo:
        image: "mongo"
        environment:
            AUTH: 'no'

